name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
  # release:
  #   types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-architecture image
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            expl0it99/marzban_metrics_exporter:latest
            # ${{ secrets.DOCKERHUB_USERNAME }}/marzban_metrics_exporter:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/marzban_metrics_exporter:latest
            # ghcr.io/${{ github.repository_owner }}/marzban_metrics_exporter:${{ github.ref_name }}